definitions:
  models.Event:
    properties:
      created_at:
        type: string
      date:
        type: string
      id:
        type: integer
      location:
        type: string
      name:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  models.FavoriteInput:
    properties:
      fighter_id:
        type: integer
    required:
    - fighter_id
    type: object
  models.Fight:
    properties:
      created_at:
        type: string
      event_id:
        description: Foreign key to Event
        type: integer
      fighter_1:
        type: string
      fighter_2:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      weight_class:
        type: string
    type: object
  models.Fighter:
    properties:
      created_at:
        type: string
      draws:
        type: integer
      first_name:
        type: string
      height:
        type: string
      id:
        type: integer
      last_name:
        type: string
      losses:
        type: integer
      name:
        type: string
      nickname:
        type: string
      updated_at:
        type: string
      weight:
        type: string
      wins:
        type: integer
    type: object
  models.LoginInput:
    properties:
      email:
        default: user@example.com
        example: test@example.com
        type: string
      password:
        default: "123456"
        example: password123
        type: string
    type: object
  models.RegisterInput:
    properties:
      email:
        default: user@example.com
        example: user@example.com
        type: string
      password:
        default: "123456"
        example: "123456"
        type: string
      username:
        default: testuser
        example: testuser
        type: string
    type: object
info:
  contact: {}
  description: This is an API for UFC Fight tracking
  title: UFC API
  version: "1.0"
paths:
  /admin/events:
    post:
      consumes:
      - application/json
      description: Admins can create a new event
      parameters:
      - description: Event Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create a new event
      tags:
      - admin
  /admin/events/{id}:
    delete:
      description: Admins can delete an event by ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete an event
      tags:
      - admin
    put:
      consumes:
      - application/json
      description: Admins can update an event by ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated Event Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Event'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update an existing event
      tags:
      - admin
  /admin/users/{id}/role:
    post:
      consumes:
      - application/json
      description: Admins can change a user's role (e.g., user → admin)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: New Role (admin/user)
        in: body
        name: request
        required: true
        schema:
          properties:
            role:
              type: string
          type: object
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Update user role
      tags:
      - admin
  /events/{event_id}/fightcard:
    get:
      description: Fetches all fights scheduled for a specific UFC event
      parameters:
      - description: Event ID
        in: path
        name: event_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fight'
            type: array
      summary: Get fight card for an event
      tags:
      - events
  /events/upcoming:
    get:
      description: Fetches a list of upcoming UFC events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Event'
            type: array
      summary: Get upcoming UFC events
      tags:
      - events
  /favorites:
    get:
      description: List all fighters favorited by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fighter'
            type: array
      security:
      - BearerAuth: []
      summary: List favorite fighters
      tags:
      - favorites
    post:
      consumes:
      - application/json
      description: Add a fighter to the authenticated user's favorites list
      parameters:
      - description: Favorite Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.FavoriteInput'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Add a fighter to favorites
      tags:
      - favorites
  /favorites/{fighter_id}:
    delete:
      description: Remove a fighter from the authenticated user's favorites list
      parameters:
      - description: Fighter ID
        in: path
        name: fighter_id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Remove a fighter from favorites
      tags:
      - favorites
  /fighters:
    get:
      parameters:
      - description: Fighter's Name
        in: query
        name: name
        type: string
      - description: Fighter's Stance (e.g., Southpaw, Orthodox)
        in: query
        name: stance
        type: string
      - description: Fighter's Weight
        in: query
        name: weight
        type: string
      - description: Minimum Wins
        in: query
        name: wins
        type: integer
      - description: Maximum Losses
        in: query
        name: losses
        type: integer
      - description: Limit number of results (default is 10)
        in: query
        name: limit
        type: integer
      - description: Offset for pagination (default is 0)
        in: query
        name: offset
        type: integer
      responses:
        "200":
          description: List of fighters
          schema:
            items:
              $ref: '#/definitions/models.Fighter'
            type: array
        "400":
          description: Invalid query parameters
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: User Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      produces:
      - application/json
      responses: {}
      summary: Login user
      tags:
      - auth
  /profile:
    get:
      consumes:
      - application/json
      description: Retrieve the authenticated user's profile using JWT token
      produces:
      - application/json
      responses:
        "200":
          description: User profile data
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - auth
  /rankings:
    get:
      consumes:
      - application/json
      description: Retrieve the rankings of fighters for a specific weight class
      parameters:
      - description: Weight class of fighters (e.g., Lightweight, Welterweight)
        in: query
        name: weightclass
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get rankings by weight class
      tags:
      - Rankings
  /register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User Registration Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegisterInput'
      produces:
      - application/json
      responses: {}
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
